// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCngoHHW7akIl64hsB0oW80h-zMZ31wqQc',
    appId: '1:1030417088033:web:fd84defe9597ebe92dad60',
    messagingSenderId: '1030417088033',
    projectId: 'gofresh1-30b2e',
    authDomain: 'gofresh1-30b2e.firebaseapp.com',
    storageBucket: 'gofresh1-30b2e.appspot.com',
    measurementId: 'G-S1QFVLTTE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Yy7R06Aop57tUKpDfFH1Ox57SzrDa9k',
    appId: '1:1030417088033:android:9f84f6e11fc6f2d72dad60',
    messagingSenderId: '1030417088033',
    projectId: 'gofresh1-30b2e',
    storageBucket: 'gofresh1-30b2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0dBxGc9s2c3jZgf7Wnpok6ZHU-RDs4c',
    appId: '1:1030417088033:ios:f81bba3f45b2ee332dad60',
    messagingSenderId: '1030417088033',
    projectId: 'gofresh1-30b2e',
    storageBucket: 'gofresh1-30b2e.appspot.com',
    iosClientId: '1030417088033-qtp0tcku7f9i2liu3mmhbl15gphe19ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.gofresh1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0dBxGc9s2c3jZgf7Wnpok6ZHU-RDs4c',
    appId: '1:1030417088033:ios:f81bba3f45b2ee332dad60',
    messagingSenderId: '1030417088033',
    projectId: 'gofresh1-30b2e',
    storageBucket: 'gofresh1-30b2e.appspot.com',
    iosClientId: '1030417088033-qtp0tcku7f9i2liu3mmhbl15gphe19ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.gofresh1',
  );
}
